### PR TITLE
Dark code blocks and navbar

### PR DESCRIPTION
**Pull request by 2E0PGS**
Make code blocks dark so they down burn your face on the page.

Make navbar background dark so its not garish.

### CODE REVIEW

**Comment by titangene** [comment]
Thanks your PR.

But I want code blocks to retain obvious blocks space. Otherwise, I will darken the code blocks background.And have changed the code highlight to Visual Studio Code dark theme.

The navbar part has been changed to a real dark theme.

You can try the style I just added.

**Comment by titangene** [comment]
Thanks your PR.

But I want code blocks to retain obvious blocks space. Otherwise, I will darken the code blocks background.And have changed the code highlight to Visual Studio Code dark theme.

The navbar part has been changed to a real dark theme.

You can try the style I just added.

**Comment by 2E0PGS** [comment]
Looking great thanks for adding those tweaks! You may want to update your screenshots on the README.md now.

Cheers!

**Comment by titangene** [comment]
I have updated the screenshot in README.md.

If there are suggestions you can tell me.
Thanks!

**Pull request closed without merging**
